site_name: CCN Access to Computing
site_url: https://garynapier.github.io/city_college/

theme:
  name: material

docs_dir: docs

nav:
  - Home: index.md
  - setup_and_org_page.md
  - unix_page.md
  - Word processing:
    - 'Hello Quarto': 'word_processing/hello_quarto.qmd'
  
markdown_extensions:
  - attr_list
  - toc: false
  
extra_css:
  - stylesheets/extra.css
  
plugins:
  - mkquartodocs