site_name: CCN Access to Computing
site_url: https://garynapier.github.io/city_college/

theme:
  name: material
  features:
    - navigation.expand

docs_dir: docs

nav:
  - Home: index.md
  - setup_and_org_page.md
  - unix_page.md
  - Word processing 3347:
    - 'Referencing in Word/Docs & Zotero': 'word_processing/referencing_with_zotero_page.md'
    - 'Hello Quarto': 'word_processing/hello_quarto/hello_quarto.qmd'
    - 'Referencing in Quarto': 'word_processing/referencing_in_quarto_page.md'
  - Critical Thinking 1511: 
    - critical_thinking_page.md
  
markdown_extensions:
  - attr_list
  - toc: false
  
extra_css:
  - stylesheets/extra.css
  
plugins:
  - mkquartodocs