---
title: "Unix/Linux and the command line"
author: "Gary Napier gary.napier@ccn.ac.uk"
format:
  revealjs:
    smaller: true
    logo: img/ccn_logo.png
    css: ../quarto/slides_styles.css
    footer: "Access to Computing - Unix/Linux and command line"
    embed-resources: true
---

# Command line basics

## Command line basics

- What is the command line?
- Basically, every time you do anything on a computer, like double click on a file to open it, delete a file or start an application, something is happening "in the background".
- In other words, some code is being executed. 
- The command line is just a way of by-passing all the point-and-click/drag-and-drop, and instead running those commands directly with code. 
- This means you can program the computer to execute a set of instructions. 
- Plus it's very powerful as there are loads of commands and options, and you can hack the system to your liking and just interact with it in a very flexible way. 

## Command line basics

‼️DANGER‼️️

- The command line is very powerful, especially the command `rm` ("remove")
  - This will delete files without asking if you're sure, and there's no way to retrieve it (no Recycle bin!)
  - It's even possible to erase your entire machine with one line of `rm` code and certain arguments to the command. 

## Command line basics

- How to STOP a process

`ctrl + C`

- Also `ctrl` (NOT `command`) on Mac

## Command line basics

- Open a terminal, should see:

```
<username>$

```


## Command line basics

Try a few simple commands:

```
ls
ls -a
ls -a -l
ls -a -l -h
ls -alh
ls -alh Documents
echo "hello"
cd Documents
cd ../

```
## Command line basics

Meaning:

|Command | Meaning |
|:--------|:--------|
| ls | List files |
| ls -a | List all files (including hidden) |
| ls -a -l | List all files and put them in a neat list, displaying properties |
| ls -a -l -h | List all files and put them in a neat list, displaying properties, and make human readable |
| ls -alh  | Same as above but don't need `-` for every flag |
| ls -alh Documents |  | List all files and put them in a neat list, displaying properties, in the Docuemtns folder |
| echo "hello" | Print the string "Hello" |
| cd Documents | Change directory to Documents |
| cd ../ | Change directory to one level up |

## Command line basics

Parts of a command:

| Command | Flag (option) | Argument |
|:--------:|:--------:|:--------:|
| ls | | |
| ls | -a |  |
| ls | -a -l | | 
| ls | -a -l -h | | 
| ls | -alh | |
| ls | -alh | Documents | 
| Do this... | in this way... | to this object |

## Command line basics

Other basic commands:

| Command | Meaning |
|:--------|:--------|
| cp [file] [dir] | copy |
| mv [file] [dir] | move (or rename) |
| rm [file] | remove ‼️DANGER‼️️ |
| pwd | Print Working Directory |
| mkdir [dir name] | Make new Directory |
| cat [file] | print the contents of a file |
| less [file] | print contents of a file (but allows scrolling; press q to escape) |

## Command line basics

**Navigation**

- Knowing where you are is key to using the command line.
- Where a file is is called the **path**.
- Run `cd ~/` to navigate to the home directory
- Run `pwd` (Print Working Directory) to see where you are. 
  - Should see `/c/Users/<username>`
- Run `ls Documents` to see what's in there. 
- Now `cd` into Documents. 
- Run `mkdir test_dir` (never spaces, remember! Now you can see why we don't use spaces)
- `cd test_dir`
- Now try `ls Documents` again
- Should see `ls: cannot access 'Documents': No such file or directory`
- This is because the file arguments to the commands are *relative* to the current working directory
- To refer to the `Documents` path, you have to "go up one"
- We're currently in the `test_dir` file, so that's out current working directory
- `Documents` is here relative to `test_dir`:

## Command line basics

**Navigation**

```
  ├── ~/
  ├── Documents
    └── test_dir
```

## Command line basics

**Navigation**

- It's good to have a mental model of this "tree" structure when you're navigating the paths 
  - In fact you can print this tree out if you download the `tree` package: `sudo apt-get install tree`
  
- So, to list files in `Documents` (one level up) we do `ls ../`
- `../` is a special string to go one up and you can repeat this as many times as you want to get to a file:
  - `../../../<file>`
  - `../../../<dir>/<dir>/<file>`
  
## Tips 

- Tab-completion
  - As you're typing it becomes a pain to write out things like the commands and paths file names.
  - Start typing e.g. the file path and hit **tab**. It should complete the name of the file if it's there. 
  - It will only complete the *unique* name of file once you've typed past the part that that it has in common with other file(s)
  - e.g. if I was to list the files in `Documents`, I write `Do` and hit tab and it won't complete
  - This is because we also have the `Downloads` directory, so it won't complete unit I differentiate between the two
  - Have to type at least `Doc` and then tab-complete

## Tips 

- Press up arrow key x times to get x previous commands

# Wildcards

## Wildcards - `*`

- Character `*` is a wildcard

- Matches against none or more character(s) in a file (or directory) name. 

- From `Documents` (or wherever you're choosing to work), run:

- `touch test_dir/fruit_{apples,bananas,pears}.txt`

- `touch test_dir/vegetables_{carrots,cabbages,onions}.txt`

- Now run:
- `ls test_dir/fruit_*`
- `ls test_dir/vegetables_*`

- Or even just:
- `ls test_dir/fr*`
- `ls test_dir/veg*`

Try:
- `ls test_dir/*.txt`

- What does it return?

## Wildcards - `?`

- Character `?` is also a wildcard
- Matches exactly one character. 
- So `ls ?ouse` will match files like `'house'` and `'mouse'`, but not `'grouse'`.

Try `ls test_dir/vegetables_?arrots.txt`

# Unix file structure

## Unix file structure

- Root folder is `/`. Try `ls /`

| Directory | short for | Notes |
|---|-------|-------------|
| `/bin` | binaries | Executable, compiled programs (all the commands we've been using) |
| `/dev` | devices | files that can interact with hardware |
| `/etc` | | config files - rules that govern how things run |
| `/home` | | each user lives under here (Mac uses `User`) |
| `/lib` | library | supports the programs in `bin/` (no `/lib` in Mac OSX, but there is `/usr/lib`)|
| `/sbin` | "special" binary | files like `bin/` but most can't be run directly |
| `/var` | variable | things that change all the time | 

## Unix file structure

- Under `/usr`:

`/usr/bin`

`/usr/lib`

`/usr/sbin`

`/usr/local`

## Unix file structure

- Under `/usr/local`:

`/usr/local/bin`

`/usr/local/lib`

`/usr/local/sbin`


## Unix file structure

- So what was the `~/` directory?
- This is `home/<filename>/` (or `Users/<filename>/` on Mac)

# Streams

## Streams

- What is the command line actually doing?
- Standard in
- Standard out 
- Standard error

# Piping

## Piping 

- Here's where we can start writing simple programs in the command line

- The pipe (`"|"`) takes the output of one command and passes it to the next command

- Run: `ls test_dir/veg* | grep carrot


# Text processing and sub-languages

## Text processing and sub-languages

- AWK - https://en.wikipedia.org/wiki/AWK
- sed - https://en.wikipedia.org/wiki/Sed
- grep - https://en.wikipedia.org/wiki/Grep
  - Regular expressions (regex) - https://en.wikipedia.org/wiki/Regular_expression

## Resources 

[Unix tutorial](https://dasher.wustl.edu/chem430/readings/unix-tutorial.pdf)

[Introducing the Unix Command Line](https://iopn.library.illinois.edu/pressbooks/demystifyingtechnology/back-matter/introducing-the-unix-command-line/)

[Bash tutorials](https://www.w3schools.com/bash/index.php)

[](https://matthewhiggins2017.github.io/BIO726P/practicals/Bonus_Unix_Skills/)

[csvtk](https://bioinf.shenwei.me/csvtk/) - VERY useful toolkit for dealing with csv files, file conversion, text processing and more. 



